#!/bin/sh
# This script is a faster alternative to uniq | sort
# It reads a sequence of lines from STDIN, and 
# outputs the unique lines, sorted. 

# get name of this script
command_name=$(basename "$0");
# get directory of this script
script_path=$(cd "$(dirname "$0")" || exit; pwd);
if [ "$script_path" = "" ] || [ ! -d "$script_path" ] || [ ! -e "$script_path/$command_name" ]; then echo "Variables \$command_name and \$script_path not set correctly for script $command_name"; exit 1; fi;

# command help
help_usage="
$command_name returns the sorted unique lines from STDIN

Syntax of $command_name:

[ LINES ] | $command_name 

";

# read command options
while getopts "h?" getopts_option
do
  case $getopts_option in
   h | \? ) echo "$help_usage"; exit 0;
  esac
done;
# move shell command-line-argument pointer to end of options
shift $((OPTIND - 1));

awk '{ if (! ($0 in myhash) ) { print $0 }; myhash[$0]++; }' - | sort 
